spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
        ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  port: ${SERVER_PORT}
